# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0022_add collapse arguments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptparameter',
            name='script_version',
        ),
        migrations.AddField(
            model_name='scriptparameter',
            name='script_version',
            field=models.ManyToManyField(to='wooey.ScriptVersion'),
        ),
    ]
