# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0028_update_script_subparser_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptparameter',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wooey.ScriptParser'),
        ),
    ]
