# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0028_add_script_subparser'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptversion',
            name='checksum',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='scriptparser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
