# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-15 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0030_populate-sv-m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptparametergroup',
            name='script_version',
        ),
        migrations.RemoveField(
            model_name='scriptparser',
            name='script_version',
        ),
    ]
