# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-04 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0034_update-checksums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scriptparameter',
            old_name='default',
            new_name='_default',
        ),
    ]
