# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-04 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0035_default-rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptparameter',
            name='default',
            field=jsonfield.fields.JSONField(null=True, blank=True),
        ),
    ]
