# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 09:48
from __future__ import unicode_literals
from functools import partial

from django.db import migrations, models

try:
    from jsonfield.fields import JSONCharField as JSONField

    JSONField = partial(JSONField, max_length=255)
except ImportError:
    JSONField = models.JSONField


class Migration(migrations.Migration):

    dependencies = [
        ("wooey", "0035_populate-jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptparameter",
            name="default",
            field=JSONField(blank=True, null=True),
        ),
    ]
