# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-04 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0037_populate-jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptparameter',
            name='_default',
        ),
    ]
