# Generated by Django 2.1.13 on 2019-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0041_change-script-param-to-textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptversion',
            name='kubernetes_manifest',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wooeyjob',
            name='kubernetes_pod_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scriptversion',
            name='script_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wooeyfile',
            name='filepath',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
