# Generated by Django 3.2.14 on 2023-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wooey", "0045_add_created_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptparameter",
            name="new_default",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
