# Generated by Django 3.2.14 on 2023-06-02 12:48

from django.db import migrations


def forwards_func(apps, schema_editor):
    ScriptParameter = apps.get_model("wooey", "ScriptParameter")
    for parameter in ScriptParameter.objects.all():
        parameter.new_default = parameter.default


def reverse_func(apps, schema_editor):
    ScriptParameter = apps.get_model("wooey", "ScriptParameter")
    for parameter in ScriptParameter.objects.all():
        parameter.default = parameter.new_default


class Migration(migrations.Migration):

    dependencies = [
        ("wooey", "0046_add_native_json_field"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
