# Generated by Django 3.2.14 on 2023-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wooey", "0047_migrate_default_field_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scriptparameter",
            name="default",
        ),
    ]
