# Generated by Django 3.2.14 on 2023-06-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wooey", "0048_remove_default_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scriptparameter",
            old_name="new_default",
            new_name="default",
        ),
    ]
