# Generated by Django 3.2.23 on 2023-11-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wooey", "0051_add_virtual_env"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="ignore_bad_imports",
            field=models.BooleanField(
                default=False,
                help_text="Ignore bad imports when adding scripts. This is useful if a script is under a virtual environment.",
            ),
        ),
    ]
