repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.4.11
    hooks:
      - id: biome-format
  - repo: https://github.com/rtts/djhtml
    rev: "3.0.11"
    hooks:
      - id: djhtml

default_language_version:
  python: python3.14
