repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: setup.cfg
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.4.11
    hooks:
      - id: biome-format
  - repo: https://github.com/rtts/djhtml
    rev: "3.0.11"
    hooks:
      - id: djhtml
  - repo: https://github.com/pycqa/flake8
    rev: "7.3.0"
    hooks:
      - id: flake8

default_language_version:
  python: python3.14
