# This file should be renamed to docker-compose.overrides.yml with whatever
# overrides are specific to the particular setup
version: "2.1"

services:
  wooey:
    volumes: &package-volumes
      - ../wooey:$BUILD_DIR/wooey
      # Mount over the clinto parser install if desired.
      # - ../../clinto/clinto:/usr/local/lib/python3.6/site-packages/clinto
      # if you want to run docker commands from within the container
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  celery:
    volumes: *package-volumes
