version: "2.1"
volumes:
  user_uploads:
  wooey_db:

services:
  wooey:
    extends:
      file: docker-compose.common.yml
      service: common
    ports:
      - 8081:8080
    depends_on:
      - rabbit
      - db
      - celery
    command: ./run-server

  celery:
    extends:
      file: docker-compose.common.yml
      service: common
    depends_on:
      - rabbit
      - db
    command: watchmedo auto-restart --directory=$BUILD_DIR/wooey --recursive --ignore-patterns="*.pyc" -- celery worker -A $WOOEY_PROJECT -c 4 -B -l debug -s schedule

  rabbit:
    image: rabbitmq:3.9.29-management-alpine
    ports:
      - 15672:15672

  db:
    image: postgres:13.10
    volumes:
      - wooey_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wooey
      POSTGRES_PASSWORD: wooey
      POSTGRES_DB: wooey
