# This file should be renamed to docker-compose.overrides.yml with whatever
# overrides are specific to the particular setup
version: '2.1'

services:
  wooey:
    volumes:
      - ../wooey:$BUILD_DIR/wooey
      - ../../clinto/clinto:/usr/local/lib/python3.6/site-packages/clinto
    ports:
      - 8080:8080
